<?php

namespace AppBundle\Repository;

/**
 * bestelOpdrachtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bestelOpdrachtRepository extends \Doctrine\ORM\EntityRepository
{
}
