<?php

namespace AppBundle\Repository;

/**
 * GoederenontvangstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoederenontvangstRepository extends \Doctrine\ORM\EntityRepository
{
}
